export const SET_NAME = 'SET_NAME';
export const SET_LASTNAME = 'SET_LASTNAME';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const SET_MEMBERSHIP = 'SET_MEMBERSHIP';
export const SET_FIRST_SEARCH = 'SET_FIRST_SEARCH';